[package]
authors = ["pjmp"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
description = "A npm inspired cargo subcommand for listing and updating binaries installed in $CARGO_HOME/bin."
edition = "2021"
homepage = "https://github.com/pjmp/cargo-updater"
keywords = ["cargo", "cargo-subcommand"]
license = "MIT OR Apache-2.0"
name = "cargo-updater"
readme = "README.md"
repository = "https://github.com/pjmp/cargo-updater"
resolver = "2"
version = "0.11.0"

[dependencies]
anyhow = "1.0.58"
attohttpc = {version = "0.19.1", features = ["json"]}
clap = {version = "3.2.15", default-features = false, features = ["std", "suggestions"]}
colored = "2.0.0"
semver = "1.0.12"
serde_json = "1.0.82"
term-table = "1.3.2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = 'abort'
